-- SOCIAL MEDIA DEVELOPMENT OVER RECENT DECADE SPAN 

-- VIEW: INSTAGRAM LAUNCHED OCTOBER 2010, 
--THEREFORE REACHING IT'S FIRST 190 MILLION USERS BEGINNING 2013:

ALTER VIEW INSTAGRAM_LAUNCHED
AS
SELECT [YEARS BY QUARTER], [INSTAGRAM USERS (IN MILLION)] 
FROM DBO.[SOCIAL MEDIA USERS]
WHERE [INSTAGRAM USERS (IN MILLION)] = '-'
UNION all
SELECT [YEARS BY QUARTER], [INSTAGRAM USERS (IN MILLION)]
FROM DBO.[SOCIAL MEDIA USERS]
WHERE [INSTAGRAM USERS (IN MILLION)] = '190'

select * from instagram_launched 

-- PARTITION BY 
-- INCREASE OF TOTAL USERS JOINING INSTAGRAM THROUGHOUT THE YEARS
-- HIGHEST PERCENT INCREASE JUMP (32%) IN USER REGISTRATION HAPPENED ON Q4 OF 2017

SELECT YEARS, YEARS_BY_QUARTER, [INSTAGRAM USERS (IN MILLION)], 
SUM([INSTAGRAM USERS (IN MILLION)]) OVER (PARTITION BY YEARS) AS TotalIgUsersPerYr,
[instagram users (in million)]/sum([INSTAGRAM USERS (IN MILLION)]) OVER (PARTITION BY YEARS) * 100 as PERCENT_TOTAL
from DBO.[SOCIAL MEDIA USERS]
ORDER BY [PERCENT_TOTAL] DESC;

-- CTE 
-- AVG SOCIAL MEDIA USERS DURING 2020 FOR 
-- FB: 2710.25 MILLION, TWITTER: 339.50 MILLION, INSTAGRAM: 1033 MILLION or ONE BILLION 
with CTE_SOCIALMEDIAUSERS AS (
SELECT YEARS,
AVG([FACEBOOK USERS (IN MILLION)]) AS AVG_FB_USERS_IN_MILLIONS, 
AVG([TWITTER USERS (IN MILLION)]) AS AVG_TR_USERS_IN_MILLIONS,
AVG([INSTAGRAM USERS (IN MILLION)]) AS AVG_IG_USER_IN_MILLIONS
FROM DBO.[SOCIAL MEDIA USERS]
GROUP BY YEARS)
SELECT * FROM CTE_SOCIALMEDIAUSERS

-- WAYS TO REPLACE NULL   
select 
[FACEBOOK USERS (IN MILLION)], [TWITTER USERS (IN MILLION)], 
ISNULL([INSTAGRAM USERS (IN MILLION)], 0.00) as [INSTAGRAM USERS (IN MILLION)],
coalesce([INSTAGRAM USERS (IN MILLION)], 0.00) as [INSTAGRAM USERS (IN MILLION)], 
case when [INSTAGRAM USERS (IN MILLION)] is null then 0.00 else [INSTAGRAM USERS (IN MILLION)] end
as [INSTAGRAM USERS (IN MILLION)]
FROM DBO.[SOCIAL MEDIA USERS]



